//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericAirlines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pilot : Employee
    {
        public string License { get; set; }
        public System.DateTime License_date { get; set; }
    }
}
