//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericAirlines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Flight_id { get; set; }
        public string Passenger_email { get; set; }
        public int Count { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
